-- ============================================================================
-- 0006 — role-enum migration, step N+1 of three: both vocabularies, then the
--        remap, in ONE transaction
--
-- docs/architecture/09-ROLE-ENUM-AND-OPERATION-CATALOG.md §4 is the plan this
-- file executes; §1 is the inventory of every reader it has to rewrite. The
-- order inside the file is the whole point: every gate is rewritten to accept
-- BOTH the old vocabulary (admin/tech/viewer/office) and the target one
-- (owner/office/crew_lead/crew/viewer/agent) BEFORE the first row moves, and
-- the file is one transaction, so at no committed instant does a crew
-- member's row say `crew` while `_sync_guard` only knows `tech`. `push_project`
-- calls `_sync_guard` on every field-app sync; that is the lane this order
-- protects.
--
-- BEFORE THIS RUNS, OUTSIDE THE DATABASE (doc 09 §1.2, CORRECTION 2): the
-- three edge functions that read profiles.role — gmail-proxy, qb-time-proxy,
-- qbo-proxy — must already be deployed with OFFICE_ROLES / STAFF_ROLES widened
-- to both vocabularies (this PR carries that change). They are not inside
-- this transaction. Apply this migration before that deploy and the owner
-- loses Gmail, QB Time and QBO the moment his row says `owner`.
--
-- HOW THE GATES ARE REWRITTEN. Two shapes, chosen per gate:
--   * `role_is(...)`, the new helper below, for the short gates this file
--     fully restates (_sync_guard, is_admin, the field_photos policies) and
--     for current_role_name(). It normalises whatever the row holds into the
--     target vocabulary, so a gate lists target names only and is correct on
--     both sides of the remap — and 0007's change of the column's type
--     touches none of them.
--   * a minimal diff for the four long RPCs (contact_mark_review_asked,
--     contact_merge, contact_resolve, coordination_job_patch): their bodies
--     are copied from 0000_baseline.sql verbatim, generated by script, and the
--     one `in (...)` list each carries is extended with the target names. A
--     180-line function is safer re-emitted unchanged than re-typed; the old
--     names in those lists become unreachable after 0007 and are trimmed
--     whenever each function is next touched for its own reasons.
--
-- PRODUCTION DATA TOUCHED: public.profiles.role on eleven rows, and
-- public.agents.auth_user_id on the two machine rows. Nothing else in the
-- database holds a role value. No JWT is invalidated — the Custom Access Token
-- hook is not deployed, so every helper reads profiles on each call and the
-- remap is effective at the next statement, for everyone, at once.
--
-- ROLLBACK: a failure anywhere leaves production exactly as it was. After a
-- successful commit and before 0007, the rollback is the §4.2 values list with
-- old_role and new_role swapped — every old label is still legal and every
-- gate still accepts it. That window is why 0007 waits a week.
--
-- CI: the replay database has no auth.users and therefore no profiles rows.
-- The remap statements run there and match nothing; the exact-count
-- assertions are guarded on "profiles has rows" so they bite on staging and
-- production, where they must. supabase/test/role_enum.test.sql asserts the
-- gates' behaviour with rows it creates itself.
-- ============================================================================


-- ---------------------------------------------------------------------------
-- 1. role_is(): one normalisation, one membership test.
--
-- admin → owner and tech → crew are the two old labels whose target name
-- differs. `office` and `viewer` keep their names. The `else` passthrough is
-- what current_role_name() in 0004 lacked (doc 09 CORRECTION 1): a row that
-- already holds a target name returns it instead of null.
--
-- STABLE, security definer, initplan form: evaluated once per statement, not
-- per row, and readable regardless of the caller's grant on profiles.
-- ---------------------------------------------------------------------------
create or replace function public.role_is(variadic p_roles text[]) returns boolean
  language sql
  stable
  security definer
  set search_path to 'public', 'pg_temp'
as $$
  select coalesce((
    select (case p.role::text
              when 'admin' then 'owner'
              when 'tech'  then 'crew'
              else p.role::text
            end) = any (p_roles)
      from public.profiles p
     where p.id = (select auth.uid())
  ), false);
$$;

alter function public.role_is(variadic text[]) owner to postgres;
comment on function public.role_is(variadic text[]) is
  'True when the caller''s profiles.role, normalised to the target vocabulary (admin→owner, tech→crew, else as held), is one of the given names. The one place the dual-vocabulary rule lives (doc 09 §4.1).';
-- Default privileges hand EXECUTE on every new function to anon directly, not
-- only through PUBLIC (the replay database proved it; production's is_admin()
-- carries the same anon grant). Revoke both.
revoke all on function public.role_is(variadic text[]) from public, anon;
grant execute on function public.role_is(variadic text[]) to authenticated, service_role;


-- ---------------------------------------------------------------------------
-- 2. current_role_name(): the same normalisation, with the missing `else`.
--    Signature, grants and comment unchanged from 0004.
-- ---------------------------------------------------------------------------
create or replace function public.current_role_name() returns text
  language sql
  stable
  security definer
  set search_path to 'public', 'pg_temp'
as $$
  select coalesce(
    nullif(current_setting('request.jwt.claims', true)::jsonb ->> 'role', ''),
    (select case p.role::text
              when 'admin' then 'owner'
              when 'tech'  then 'crew'
              else p.role::text
            end
       from public.profiles p
      where p.id = (select auth.uid()))
  );
$$;
-- 0004 revoked from public only; the same direct anon grant applies here.
revoke all on function public.current_role_name() from anon;


-- ---------------------------------------------------------------------------
-- 3. The gates, rewritten. Grants survive CREATE OR REPLACE; none are restated.
-- ---------------------------------------------------------------------------

-- 3a. _sync_guard — the one every field push goes through. The role check is
--     the only line that changes; the build gate and the sync_clients upsert
--     are exactly 0000_baseline.sql:291-334.
create or replace function public._sync_guard(p_build text) returns void
    language plpgsql security definer
    set search_path to 'public'
    as $$
declare min_build int; caller_build int;
begin
  if not public.role_is('owner', 'office', 'crew_lead', 'crew') then
    raise exception 'sync: this account may not write field_projects';
  end if;

  select coalesce((value)::text::int, 0) into min_build
    from public.app_settings where key = 'min_field_build';
  min_build := coalesce(min_build, 0);
  if min_build > 0 and p_build is not null then
    begin
      caller_build := regexp_replace(p_build, '\D', '', 'g')::int;
    exception when others then
      caller_build := null;
    end;
    if caller_build is not null and caller_build < min_build then
      raise exception 'sync: app build % is older than the required build % — update the app',
        caller_build, min_build
        using errcode = 'P0002';
    end if;
  end if;

  begin
    if auth.uid() is not null then
      insert into public.sync_clients (user_id, build, last_seen, calls)
      values (auth.uid(), p_build, now(), 1)
      on conflict (user_id) do update
        set build = excluded.build, last_seen = now(), calls = sync_clients.calls + 1;
    end if;
  exception when others then
    null;
  end;
end;
$$;

-- 3b. is_admin — `owner` is the admin of the target vocabulary. restore_photo
--     and the field_photos delete policy inherit this and are not touched.
create or replace function public.is_admin() returns boolean
    language sql stable security definer
    set search_path to 'public'
    as $$
  select public.role_is('owner');
$$;

-- 3c. handle_new_user — new public signups land read-only. Owner's decision
--     of 2026-09-19 (doc 09 §4.1). `viewer` is held by nobody after step 5.
create or replace function public.handle_new_user() returns trigger
    language plpgsql security definer
    set search_path to 'public'
    as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    'viewer'
  )
  on conflict (id) do nothing;
  return new;
exception when others then
  return new;
end;
$$;

-- The column default said `tech` too (0000_baseline.sql:3177); a direct
-- insert that omits role must land on the same read-only default, and 0007's
-- check constraint would reject `tech` as a default anyway.
alter table public.profiles alter column role set default 'viewer';

-- 3d. The four long RPCs, bodies verbatim from 0000_baseline.sql, one list each
--     extended. Generated: do not hand-edit the bodies here; touch the function
--     in a migration of its own when it changes for its own reasons.

CREATE OR REPLACE FUNCTION "public"."contact_mark_review_asked"("p_contact" "uuid") RETURNS boolean
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
declare
  v_uid  uuid := auth.uid();
  v_role text;
  rc     int;
begin
  if v_uid is not null then
    select p.role::text into v_role from public.profiles p where p.id = v_uid;
    if v_role is null or v_role not in ('admin', 'office', 'tech', 'owner', 'crew_lead', 'crew') then
      return false;
    end if;
  end if;
  update public.contacts
     set review_asked_at = now()
   where id = p_contact and merged_into is null and review_asked_at is null;
  get diagnostics rc = row_count;
  return rc = 1;
end;
$$;

comment on function public.contact_mark_review_asked(uuid) is
  'CF-4: the never-ask-twice review stamp. Staff roles only (in-function gate, both vocabularies until 0007); true = this call stamped it.';

CREATE OR REPLACE FUNCTION "public"."contact_merge"("p_winner" "uuid", "p_loser" "uuid") RETURNS boolean
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
declare
  v_uid  uuid := auth.uid();
  v_role text;
  v_l    public.contacts%rowtype;
  r      record;
  v_a    uuid;
  v_b    uuid;
begin
  if v_uid is not null then
    select p.role::text into v_role from public.profiles p where p.id = v_uid;
    if v_role is null or v_role not in ('admin', 'office', 'owner') then
      return false;
    end if;
  end if;

  if p_winner is null or p_loser is null or p_winner = p_loser then return false; end if;

  perform pg_advisory_xact_lock(hashtext('roybal.contact_resolve'));

  select * into v_l from public.contacts where id = p_loser  and merged_into is null;
  if v_l.id is null then return false; end if;
  perform 1 from public.contacts where id = p_winner and merged_into is null;
  if not found then return false; end if;

  update public.contacts w set
    phone   = case when w.phone   = '' then v_l.phone   else w.phone   end,
    email   = case when w.email   = '' then v_l.email   else w.email   end,
    address = case when w.address = '' then v_l.address else w.address end,
    company = case when w.company = '' then v_l.company else w.company end,
    notes   = case when v_l.notes = '' then w.notes
                   when w.notes  = ''  then v_l.notes
                   else w.notes || E'\n' || v_l.notes end,
    qbo_customer_id  = coalesce(w.qbo_customer_id, v_l.qbo_customer_id),
    marketing_opt_in = w.marketing_opt_in or v_l.marketing_opt_in,
    review_asked_at  = greatest(w.review_asked_at, v_l.review_asked_at)
  where w.id = p_winner;

  update public.contacts set merged_into = p_winner where id = p_loser;
  update public.contacts set merged_into = p_winner where merged_into = p_loser;

  update public.unified_jobs   set contact_id = p_winner where contact_id = p_loser;
  update public.sms_messages   set contact_id = p_winner where contact_id = p_loser;
  update public.email_messages set contact_id = p_winner where contact_id = p_loser;
  update public.portal_jobs    set contact_id = p_winner where contact_id = p_loser;
  update public.capture_events set contact_id = p_winner where contact_id = p_loser;

  for r in select id from public.coordination_jobs
            where deleted = false and data->>'contactId' = p_loser::text
  loop
    perform public.coordination_job_patch(r.id, jsonb_build_object('contactId', p_winner::text));
  end loop;

  update public.contact_merge_suggestions
     set status = 'merged', resolved_at = now()
   where status = 'open' and contact_b is not null
     and contact_a in (p_winner, p_loser) and contact_b in (p_winner, p_loser);

  for r in select * from public.contact_merge_suggestions
            where status = 'open' and (contact_a = p_loser or contact_b = p_loser)
  loop
    v_a := case when r.contact_a = p_loser then p_winner else r.contact_a end;
    v_b := case when r.contact_b = p_loser then p_winner else r.contact_b end;
    if v_a = v_b then
      delete from public.contact_merge_suggestions where id = r.id;
    else
      begin
        update public.contact_merge_suggestions
           set contact_a = v_a, contact_b = v_b where id = r.id;
      exception when unique_violation then
        delete from public.contact_merge_suggestions where id = r.id;
      end;
    end if;
  end loop;

  return true;
end;
$$;

comment on function public.contact_merge(uuid, uuid) is
  'Office-only merge (owner/office, plus the old admin/office names until 0007): unions blanks into the winner, tombstones the loser, repoints the five link columns AND the board blob contactId (230, via coordination_job_patch), closes the pair''s suggestions, repoints the rest.';

CREATE OR REPLACE FUNCTION "public"."contact_resolve"("p_name" "text", "p_phone" "text", "p_email" "text", "p_address" "text", "p_source" "text" DEFAULT ''::"text", "p_trusted" boolean DEFAULT false, "p_role" "text" DEFAULT 'customer'::"text") RETURNS "uuid"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
declare
  v_uid     uuid := auth.uid();
  v_caller_role  text;
  v_caller_email text;
  v_trusted boolean := coalesce(p_trusted, false);
  v_name    text := left(btrim(coalesce(p_name, '')), 200);
  v_phone   text := left(btrim(coalesce(p_phone, '')), 40);
  v_email   text := left(btrim(coalesce(p_email, '')), 320);
  v_addr    text := left(btrim(coalesce(p_address, '')), 500);
  v_source  text := left(btrim(coalesce(p_source, '')), 80);
  v_role    text := left(btrim(coalesce(nullif(p_role, ''), 'customer')), 40);
  v_name_n  text;
  v_phone_n text;
  v_email_n text;
  v_street  text;
  v_id      uuid;
  v_new     uuid;
  v_row     public.contacts%rowtype;
  v_diff    jsonb;
begin
  v_name_n  := lower(v_name);
  v_phone_n := right(regexp_replace(v_phone, '\D', '', 'g'), 10);
  v_email_n := lower(v_email);

  -- caller gate (fail closed)
  if v_uid is not null then
    select p.role::text, u.email into v_caller_role, v_caller_email
      from public.profiles p join auth.users u on u.id = p.id
     where p.id = v_uid;
    if v_caller_role in ('admin', 'office', 'tech', 'owner', 'crew_lead', 'crew') then
      null;
    elsif v_caller_role in ('viewer', 'agent') and v_caller_email = 'phone-agent@roybalconstruction.com' then
      v_trusted := false;
    else
      return null;
    end if;
  end if;

  if v_name = '' and v_phone_n = '' and v_email_n = '' then
    return null;
  end if;

  perform pg_advisory_xact_lock(hashtext('roybal.contact_resolve'));

  -- 0. exact identity — idempotent re-entry
  select id into v_id from public.contacts
   where lower(btrim(name)) = v_name_n
     and phone_norm = v_phone_n
     and email_norm = v_email_n
     and lower(btrim(address)) = lower(v_addr)
   order by (merged_into is null) desc, created_at
   limit 1;
  if v_id is not null then
    return public.contact_canonical(v_id);
  end if;

  -- 1. exact 10-digit phone
  if length(v_phone_n) = 10 then
    select id into v_id from public.contacts
     where phone_norm = v_phone_n
     order by (merged_into is null) desc, created_at
     limit 1;
    if v_id is not null then
      v_id := public.contact_canonical(v_id);
      select * into v_row from public.contacts where id = v_id;

      v_diff := jsonb_strip_nulls(jsonb_build_object(
        'name',    case when v_name_n  <> '' and lower(btrim(v_row.name))  <> v_name_n  then jsonb_build_object('have', v_row.name,    'got', v_name)  end,
        'email',   case when v_email_n <> '' and v_row.email <> '' and lower(btrim(v_row.email)) <> v_email_n then jsonb_build_object('have', v_row.email, 'got', v_email) end,
        'address', case when v_addr    <> '' and v_row.address <> '' and lower(btrim(v_row.address)) <> lower(v_addr) then jsonb_build_object('have', v_row.address, 'got', v_addr) end));
      if v_diff <> '{}'::jsonb then
        insert into public.contact_merge_suggestions (contact_a, reason, detail, source)
        values (v_id, 'conflict', v_diff, v_source)
        on conflict do nothing;
      end if;

      if v_trusted then
        update public.contacts set
          email   = case when email   = '' and v_email_n <> '' then v_email else email end,
          address = case when address = '' and v_addr    <> '' then v_addr  else address end
        where id = v_id;
      elsif (v_row.email = '' and v_email_n <> '') or (v_row.address = '' and v_addr <> '') then
        insert into public.contact_merge_suggestions (contact_a, reason, detail, source)
        values (v_id, 'untrusted-fill', jsonb_strip_nulls(jsonb_build_object(
                  'email',   case when v_row.email   = '' and v_email_n <> '' then v_email end,
                  'address', case when v_row.address = '' and v_addr    <> '' then v_addr end)),
                v_source)
        on conflict do nothing;
      end if;
      return v_id;
    end if;
  end if;

  -- 2. exact email
  if v_email_n <> '' then
    select id into v_id from public.contacts
     where email_norm = v_email_n
     order by (merged_into is null) desc, created_at
     limit 1;
    if v_id is not null then
      v_id := public.contact_canonical(v_id);
      select * into v_row from public.contacts where id = v_id;

      if v_name_n = '' then
        return v_id;
      end if;

      if v_trusted and lower(btrim(v_row.name)) = v_name_n then
        v_diff := jsonb_strip_nulls(jsonb_build_object(
          'phone',   case when v_phone_n <> '' and v_row.phone <> '' and right(regexp_replace(v_row.phone,'\D','','g'),10) <> v_phone_n then jsonb_build_object('have', v_row.phone, 'got', v_phone) end,
          'address', case when v_addr <> '' and v_row.address <> '' and lower(btrim(v_row.address)) <> lower(v_addr) then jsonb_build_object('have', v_row.address, 'got', v_addr) end));
        if v_diff <> '{}'::jsonb then
          insert into public.contact_merge_suggestions (contact_a, reason, detail, source)
          values (v_id, 'conflict', v_diff, v_source)
          on conflict do nothing;
        end if;
        update public.contacts set
          phone   = case when phone   = '' and v_phone_n <> '' then v_phone else phone end,
          address = case when address = '' and v_addr    <> '' then v_addr  else address end
        where id = v_id;
        return v_id;
      end if;

      insert into public.contacts (name, phone, email, address, source, role)
      values (v_name, v_phone, v_email, v_addr, v_source, v_role)
      returning id into v_new;
      insert into public.contact_merge_suggestions (contact_a, contact_b, reason, detail, source)
      values (v_id, v_new, 'email', jsonb_build_object('email', v_email_n), v_source)
      on conflict do nothing;
      return v_new;
    end if;
  end if;

  -- 3. same name + same street number → create + suggestion
  v_street := (regexp_match(v_addr, '^\s*(\d+)'))[1];
  if v_name_n <> '' and v_street is not null then
    select id into v_id from public.contacts
     where merged_into is null
       and lower(btrim(name)) = v_name_n
       and (regexp_match(btrim(address), '^\s*(\d+)'))[1] = v_street
     order by created_at limit 1;
    if v_id is not null then
      insert into public.contacts (name, phone, email, address, source, role)
      values (v_name, v_phone, v_email, v_addr, v_source, v_role)
      returning id into v_new;
      insert into public.contact_merge_suggestions (contact_a, contact_b, reason, detail, source)
      values (v_id, v_new, 'name-address', jsonb_build_object('name', v_name, 'street', v_street), v_source)
      on conflict do nothing;
      return v_new;
    end if;
  end if;

  -- 4. bare exact-name match — fragments must not bypass the queue
  if v_name_n <> '' then
    select id into v_id from public.contacts
     where merged_into is null and lower(btrim(name)) = v_name_n
     order by created_at limit 1;
    if v_id is not null then
      insert into public.contacts (name, phone, email, address, source, role)
      values (v_name, v_phone, v_email, v_addr, v_source, v_role)
      returning id into v_new;
      insert into public.contact_merge_suggestions (contact_a, contact_b, reason, detail, source)
      values (v_id, v_new, 'name', jsonb_build_object('name', v_name), v_source)
      on conflict do nothing;
      return v_new;
    end if;
  end if;

  -- 5. a new person (never a nameless shell)
  insert into public.contacts (name, phone, email, address, source, role)
  values (coalesce(nullif(v_name, ''), nullif(v_email, ''), v_phone_n), v_phone, v_email, v_addr, v_source, v_role)
  returning id into v_id;
  return v_id;
end;
$$;


CREATE OR REPLACE FUNCTION "public"."coordination_job_patch"("p_id" "uuid", "p_patch" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
declare
  v_uid  uuid := auth.uid();
  v_role text;
  v_data jsonb;
  v_rev  int;
  v_prev timestamptz;
  v_ts   text;
begin
  -- 246: a JWT caller must be a verified office user (the contact_merge
  -- gate). Refusal is a null no-op, same as a missing row — this function
  -- must not become an existence oracle for job ids.
  if v_uid is not null then
    select p.role::text into v_role from public.profiles p where p.id = v_uid;
    if v_role is null or v_role not in ('admin', 'office', 'owner') then
      return null;
    end if;
  end if;

  select data into v_data from public.coordination_jobs
    where id = p_id and deleted = false
    for update;                                  -- serialize against a concurrent board save
  if v_data is null then return null; end if;    -- gone or tombstoned → no-op, not an error

  v_rev := coalesce((v_data->>'rev')::int, 0) + 1;
  -- prior timestamp, tolerant of a missing OR malformed updatedAt (the 218/225
  -- precedent: a bare ('')::timestamptz raises 22007 and coalesce can't catch it)
  begin v_prev := (v_data->>'updatedAt')::timestamptz; exception when others then v_prev := null; end;
  -- strictly newer than what's on file and not behind the clock (the 218 rule)
  v_ts := to_char(greatest(now(), coalesce(v_prev, to_timestamp(0)) + interval '1 ms')
            at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');

  -- shallow merge (patch keys win), then OVERLAY rev+updatedAt so the caller
  -- can never set them — they are function-controlled
  v_data := (v_data || p_patch) || jsonb_build_object('rev', v_rev, 'updatedAt', v_ts);
  update public.coordination_jobs set data = v_data where id = p_id;   -- coordination_touch() stamps the updated_at COLUMN
  return v_data;
end;
$$;

comment on function public.coordination_job_patch(uuid, jsonb) is
  'Board Tier 1 + CRM §13.3: rev-bumping shallow patch of a coordination_jobs blob so the board adopts (not clobbers) the change. service_role, or a JWT whose profiles.role is owner|office (admin until 0007; others: null no-op).';

-- 3e. field_photos — three policies replaced in place (same names, same
--     count); field_photos_admin_delete stays on is_admin(). The read policy
--     gains `agent` because the two machine accounts that read today as
--     `viewer` become `agent` in step 5.
drop policy if exists field_photos_crew_read on public.field_photos;
create policy field_photos_crew_read on public.field_photos
  for select to authenticated
  using (public.role_is('owner', 'office', 'crew_lead', 'crew', 'viewer', 'agent'));

drop policy if exists field_photos_crew_update on public.field_photos;
create policy field_photos_crew_update on public.field_photos
  for update to authenticated
  using (public.role_is('owner', 'office', 'crew_lead', 'crew'))
  with check (public.role_is('owner', 'office', 'crew_lead', 'crew'));

drop policy if exists field_photos_crew_write on public.field_photos;
create policy field_photos_crew_write on public.field_photos
  for insert to authenticated
  with check (public.role_is('owner', 'office', 'crew_lead', 'crew'));

-- 3f. sync_fleet — the status arm compares text, so the view no longer pins the
--     column's enum type (0007 has to drop and recreate it anyway; this is the
--     definition it recreates). Body otherwise verbatim from the baseline.
CREATE OR REPLACE VIEW "public"."sync_fleet" AS
 SELECT "u"."email",
    ("p"."role")::"text" AS "role",
    "c"."build",
    "c"."last_seen",
    "c"."calls",
        CASE
            WHEN (("p"."role")::"text" = ANY (ARRAY['viewer'::"text", 'agent'::"text"])) THEN 'n/a (service account)'::"text"
            WHEN ("c"."user_id" IS NULL) THEN 'never synced through the RPC'::"text"
            WHEN ("c"."last_seen" < ("now"() - '3 days'::interval)) THEN 'quiet 3+ days'::"text"
            ELSE 'ok'::"text"
        END AS "status"
   FROM (("public"."profiles" "p"
     JOIN "auth"."users" "u" ON (("u"."id" = "p"."id")))
     LEFT JOIN "public"."sync_clients" "c" ON (("c"."user_id" = "p"."id")))
  ORDER BY ("c"."last_seen" IS NULL) DESC, "c"."last_seen" DESC NULLS LAST;



-- ---------------------------------------------------------------------------
-- 4. Every gate now answers to both vocabularies. Assert the sync path still
--    resolves BEFORE any row moves, so a broken rewrite stops the file here.
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.proname = '_sync_guard'
       and pg_get_function_identity_arguments(p.oid) = 'p_build text'
  ) then
    raise exception 'push_project can no longer resolve _sync_guard(p_build text)';
  end if;
  if pg_get_functiondef('public.current_role_name()'::regprocedure) !~ 'else p\.role::text' then
    raise exception 'current_role_name() lost its else passthrough';
  end if;
end
$$;


-- ---------------------------------------------------------------------------
-- 5. The remap. doc 09 §4.2 / §5.2, as the owner named the people on
--    2026-09-19. Keyed on auth.users.email because a reviewer can check an
--    email against the admin's user list and cannot check a uuid against
--    anything. Never a blanket `set role = 'owner' where role = 'admin'`.
--
--    TODO BEFORE APPLYING (doc 09 §5.2 (2)): the three placeholder emails
--    below end in "@TODO". The guard in step 6 refuses to commit against a
--    database that has profiles while any placeholder remains, so this file
--    cannot be applied to staging or production by accident.
-- ---------------------------------------------------------------------------
create temporary table role_remap (email text, old_role text, new_role text) on commit drop;
insert into role_remap (email, old_role, new_role) values
  ('branden@roybalconstruction.com',      'admin',  'owner'),      -- Branden Roybal, owner
  ('cj@TODO',                             'admin',  'crew_lead'),  -- CJ (Clinton Smith), Project Manager; holds the second admin login
  ('david.jarman@TODO',                   'tech',   'crew_lead'),  -- lead carpenter, runs a crew
  ('gregory.costa@TODO',                  'tech',   'crew_lead'),  -- lead carpenter, runs a crew
  ('phone-agent@roybalconstruction.com',  'viewer', 'agent'),
  ('office-brief@roybalconstruction.com', 'viewer', 'agent');

do $$
declare
  n_profiles int;
  n_named    int;
  n_crew     int;
begin
  select count(*) into n_profiles from public.profiles;

  -- 5a. the named rows
  update public.profiles p
     set role = r.new_role::public.user_role
    from role_remap r
    join auth.users u on lower(u.email) = lower(r.email)
   where p.id = u.id
     and p.role::text = r.old_role;   -- a row already moved is skipped, not clobbered
  get diagnostics n_named = row_count;

  -- 5b. everyone still holding tech is a crew member (03 §2.4: tech → crew) —
  --     the five techs the owner did not name, reviewed per doc 09 §5.2 (3).
  update public.profiles set role = 'crew' where role::text = 'tech';
  get diagnostics n_crew = row_count;

  -- 5c. the machine rows get their agents link (fixed ids from 0004:966-973)
  update public.agents a set auth_user_id = u.id
    from auth.users u
   where a.id = '4b3353d3-6b71-49f6-94df-c79b959f0eb5'          -- agent:phone
     and lower(u.email) = 'phone-agent@roybalconstruction.com';
  update public.agents a set auth_user_id = u.id
    from auth.users u
   where a.id = '1af33481-7f1c-4485-87f5-7b0ec5e27554'          -- agent:brief
     and lower(u.email) = 'office-brief@roybalconstruction.com';

  raise notice 'role remap: % profiles, % named rows moved, % tech → crew', n_profiles, n_named, n_crew;

  -- 6. The assertions. Trivial on the CI replay (no rows); binding everywhere
  --    that has people. Any mismatch means the fleet is not what the owner
  --    reviewed, and the answer is to re-decide the list, not to bend it here.
  if n_profiles > 0 then
    if exists (select 1 from role_remap where email like '%@TODO') then
      raise exception 'role remap: placeholder emails remain in the values list (doc 09 §5.2 (2)); fill them in before applying';
    end if;
    if n_profiles <> 11 then
      raise exception 'role remap: expected 11 profiles, found % — the fleet changed since the reviewed list; re-decide the mapping', n_profiles;
    end if;
    if n_named <> 6 then
      raise exception 'role remap: expected 6 named rows to move, moved % — an email in the list did not match a row with the expected old role', n_named;
    end if;
    if n_crew <> 5 then
      raise exception 'role remap: expected 5 tech → crew rows, moved %', n_crew;
    end if;
    if (select count(*) filter (where role::text = 'owner')     from public.profiles) <> 1
    or (select count(*) filter (where role::text = 'crew_lead') from public.profiles) <> 3
    or (select count(*) filter (where role::text = 'crew')      from public.profiles) <> 5
    or (select count(*) filter (where role::text = 'agent')     from public.profiles) <> 2
    or (select count(*) filter (where role::text = 'office')    from public.profiles) <> 0 then
      raise exception 'role remap: final distribution is not 1 owner / 3 crew_lead / 5 crew / 2 agent / 0 office';
    end if;
    if (select count(*) from public.agents where auth_user_id is not null) < 2 then
      raise exception 'role remap: the two machine accounts were not linked to their agents rows';
    end if;
  end if;

  -- holds at zero rows too: nothing may be left in the old vocabulary's
  -- two renamed labels once this file commits.
  if exists (select 1 from public.profiles where role::text in ('admin', 'tech')) then
    raise exception 'role remap incomplete: a profile still holds admin or tech';
  end if;
end
$$;
